services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "42069:42069"
    environment:
      DATABASE_URL: postgres://postgres:admin@db:5432/postgres
    depends_on:
      - db
    volumes:
      - .:/app
    command: ["go", "run", "backend/main.go"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"

  db:
    image: postgres:16 
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postrges 
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
